console.log(' 1) Select the section with an id of container without using querySelector.');
let element = document.getElementById('container');
console.log(element);
console.log(' 2) Select the section with an id of container using querySelector.');
element = document.querySelector('#container');
console.log(element);
console.log(' 3) Select all of the list items with a class of "second".');
let elements = document.getElementsByClassName('second');
console.log(elements);
console.log(' 4) Select a list item with a class of third, but only the list item inside of the ol tag.');
elements = document.querySelectorAll('ol .third');
console.log(elements);
console.log(' 5) Give the section with an id of container the text "Hello!".');
element = document.getElementById('container');
element.innerHTML = 'Hello!' + element.innerHTML;
console.log(' 6) Add the class main to the div with a class of footer.');
element = document.getElementsByClassName('footer')[0];
element.classList.add('main');
console.log(`Class names: ${element.classList}`);
console.log(' 7) Remove the class main on the div with a class of footer.');
element = document.getElementsByClassName('footer')[0];
element.classList.remove('main');
console.log(`Class names: ${element.classList}`);
console.log(' 8) Create a new li element.');
element = document.createElement('li');
console.log(' 9) Give the li the text "four".');
element.innerHTML = 'four';
console.log(' 10) Append the li to the ul element.');
let ul = document.querySelector('ul');
ul.appendChild(element);
console.log(' 12) Loop over all of the lis inside the ol tag and give them a background color of "green".');
let ol = document.querySelector('ol');
console.log(ol);
for (const element of ol.children) {
	console.log(element);
	element.style.color = 'green';
}
console.log(' 13) Remove the div with a class of footer.');
element = document.getElementsByClassName('footer')[0];
element.remove();
